---
- hosts: webserver
  remote_user: root
  become: yes
  tasks:
    - copy:
        src: docker
        dest: ansible

    - name: Build Image
      shell: docker build -t web ansible/docker/

    - name: Create Container
      shell: docker run -dP web

    - name: Check if container is running
      shell: docker ps
